"""cert-metadata

Revision ID: 1172d94d6460
Revises: 6b77f68420c5
Create Date: 2026-03-05 16:48:35.107178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1172d94d6460'
down_revision: Union[str, Sequence[str], None] = '6b77f68420c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certs', sa.Column('person_fullname', sa.String(), nullable=True))
    op.add_column('certs', sa.Column('certificate', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certs', 'certificate')
    op.drop_column('certs', 'person_fullname')
    # ### end Alembic commands ###
