"""pc

Revision ID: 489ace90ea0a
Revises: c489df4caea4
Create Date: 2026-03-05 14:39:59.919129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '489ace90ea0a'
down_revision: Union[str, Sequence[str], None] = 'c489df4caea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pcs', sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('pcs', 'cpu')
    op.drop_column('pcs', 'motherboard')
    op.drop_column('pcs', 'ram')
    op.drop_column('pcs', 'storage')
    op.drop_column('pcs', 'gpu')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pcs', sa.Column('gpu', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pcs', sa.Column('storage', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pcs', sa.Column('ram', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pcs', sa.Column('motherboard', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pcs', sa.Column('cpu', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pcs', 'spec')
    # ### end Alembic commands ###
