"""pc-history

Revision ID: 6b77f68420c5
Revises: 489ace90ea0a
Create Date: 2026-03-05 15:26:16.718239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b77f68420c5'
down_revision: Union[str, Sequence[str], None] = '489ace90ea0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pcs', sa.Column('spec_history', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pcs', 'spec_history')
    # ### end Alembic commands ###
