"""pc

Revision ID: c489df4caea4
Revises: 
Create Date: 2026-03-05 11:45:14.016235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c489df4caea4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pc_parts')
    op.add_column('pcs', sa.Column('motherboard', sa.String(length=255), nullable=True))
    op.add_column('pcs', sa.Column('cpu', sa.String(length=255), nullable=True))
    op.add_column('pcs', sa.Column('ram', sa.String(length=255), nullable=True))
    op.add_column('pcs', sa.Column('storage', sa.String(length=255), nullable=True))
    op.add_column('pcs', sa.Column('gpu', sa.String(length=255), nullable=True))
    op.add_column('pcs', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pcs', 'timestamp')
    op.drop_column('pcs', 'gpu')
    op.drop_column('pcs', 'storage')
    op.drop_column('pcs', 'ram')
    op.drop_column('pcs', 'cpu')
    op.drop_column('pcs', 'motherboard')
    op.create_table('pc_parts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('domain_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pc_parts_pkey')),
    sa.UniqueConstraint('domain_name', name=op.f('pc_parts_domain_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('pc_parts_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
